export const PRODUCT_CATEGORIES = [
  "Automotivo",
  "Banheiro",
  "Bebês",
  "Bebidas",
  "Brinquedos",
  "Capinhas e Acessórios",
  "Casa",
  "Casa e Decoração",
  "Calçados",
  "Celulares",
  "Cosméticos e Perfumes",
  "Cozinha",
  "Decoração Comemorativa",
  "Eletrodomésticos",
  "Eletrônicos",
  "Ferramentas",
  "Instrumentos Musicais",
  "Mochilas",
  "Móveis",
  "Moda e Acessórios",
  "Notebooks",
  "Papelaria",
  "Pesca",
  "Pet",
  "Produtos de Limpeza",
  "Roupas",
  "Saúde e Bem-Estar",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

