/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirecionandoRouteImport } from './routes/redirecionando'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as EtiquetaIdRouteImport } from './routes/etiqueta.$id'
import { Route as AuthenticatedMeusPedidosRouteImport } from './routes/_authenticated/meus-pedidos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminReembolsosRouteImport } from './routes/_authenticated/admin.reembolsos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminExpedicaoRouteImport } from './routes/_authenticated/admin.expedicao'
import { Route as AuthenticatedAdminEquipeRouteImport } from './routes/_authenticated/admin.equipe'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp.webhook'

const RedirecionandoRoute = RedirecionandoRouteImport.update({
  id: '/redirecionando',
  path: '/redirecionando',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EtiquetaIdRoute = EtiquetaIdRouteImport.update({
  id: '/etiqueta/$id',
  path: '/etiqueta/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeusPedidosRoute =
  AuthenticatedMeusPedidosRouteImport.update({
    id: '/meus-pedidos',
    path: '/meus-pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReembolsosRoute =
  AuthenticatedAdminReembolsosRouteImport.update({
    id: '/reembolsos',
    path: '/reembolsos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExpedicaoRoute =
  AuthenticatedAdminExpedicaoRouteImport.update({
    id: '/expedicao',
    path: '/expedicao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEquipeRoute =
  AuthenticatedAdminEquipeRouteImport.update({
    id: '/equipe',
    path: '/equipe',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/redirecionando': typeof RedirecionandoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reembolsos': typeof AuthenticatedAdminReembolsosRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/redirecionando': typeof RedirecionandoRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/reembolsos': typeof AuthenticatedAdminReembolsosRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/redirecionando': typeof RedirecionandoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/meus-pedidos': typeof AuthenticatedMeusPedidosRoute
  '/etiqueta/$id': typeof EtiquetaIdRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/produto/$id': typeof ProdutoIdRoute
  '/_authenticated/admin/equipe': typeof AuthenticatedAdminEquipeRoute
  '/_authenticated/admin/expedicao': typeof AuthenticatedAdminExpedicaoRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/reembolsos': typeof AuthenticatedAdminReembolsosRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/redirecionando'
    | '/admin'
    | '/meus-pedidos'
    | '/etiqueta/$id'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/equipe'
    | '/admin/expedicao'
    | '/admin/pedidos'
    | '/admin/reembolsos'
    | '/api/public/mp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/redirecionando'
    | '/admin'
    | '/meus-pedidos'
    | '/etiqueta/$id'
    | '/pedido/$id'
    | '/produto/$id'
    | '/admin/equipe'
    | '/admin/expedicao'
    | '/admin/pedidos'
    | '/admin/reembolsos'
    | '/api/public/mp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/redirecionando'
    | '/_authenticated/admin'
    | '/_authenticated/meus-pedidos'
    | '/etiqueta/$id'
    | '/pedido/$id'
    | '/produto/$id'
    | '/_authenticated/admin/equipe'
    | '/_authenticated/admin/expedicao'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/reembolsos'
    | '/api/public/mp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  LojaRoute: typeof LojaRoute
  RedirecionandoRoute: typeof RedirecionandoRoute
  EtiquetaIdRoute: typeof EtiquetaIdRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirecionando': {
      id: '/redirecionando'
      path: '/redirecionando'
      fullPath: '/redirecionando'
      preLoaderRoute: typeof RedirecionandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etiqueta/$id': {
      id: '/etiqueta/$id'
      path: '/etiqueta/$id'
      fullPath: '/etiqueta/$id'
      preLoaderRoute: typeof EtiquetaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meus-pedidos': {
      id: '/_authenticated/meus-pedidos'
      path: '/meus-pedidos'
      fullPath: '/meus-pedidos'
      preLoaderRoute: typeof AuthenticatedMeusPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reembolsos': {
      id: '/_authenticated/admin/reembolsos'
      path: '/reembolsos'
      fullPath: '/admin/reembolsos'
      preLoaderRoute: typeof AuthenticatedAdminReembolsosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/expedicao': {
      id: '/_authenticated/admin/expedicao'
      path: '/expedicao'
      fullPath: '/admin/expedicao'
      preLoaderRoute: typeof AuthenticatedAdminExpedicaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/equipe': {
      id: '/_authenticated/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AuthenticatedAdminEquipeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEquipeRoute: typeof AuthenticatedAdminEquipeRoute
  AuthenticatedAdminExpedicaoRoute: typeof AuthenticatedAdminExpedicaoRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminReembolsosRoute: typeof AuthenticatedAdminReembolsosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEquipeRoute: AuthenticatedAdminEquipeRoute,
  AuthenticatedAdminExpedicaoRoute: AuthenticatedAdminExpedicaoRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminReembolsosRoute: AuthenticatedAdminReembolsosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMeusPedidosRoute: typeof AuthenticatedMeusPedidosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMeusPedidosRoute: AuthenticatedMeusPedidosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  LojaRoute: LojaRoute,
  RedirecionandoRoute: RedirecionandoRoute,
  EtiquetaIdRoute: EtiquetaIdRoute,
  PedidoIdRoute: PedidoIdRoute,
  ProdutoIdRoute: ProdutoIdRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
